# Generated by Django 5.0.3 on 2024-03-22 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('CS', 'Cheese Slice'), ('WH', 'Waffer'), ('ST', 'Stationary'), ('BS', 'Biscut'), ('SP', 'Soap'), ('DT', 'Detergent'), ('CD', 'Cold Drink'), ('BT', 'Beauty'), ('OR', 'Oral'), ('DR', 'Dairy'), ('SH', 'Shampoo')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
